# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bookShare' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  # Pods for bookShare

  target 'bookShareTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'bookShare-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bookShare-tvOS

  target 'bookShare-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
